baseurl = "https://eclipse.dev/quneiform"
DefaultContentLanguage = "en"
title = "i18n & l10n Analysis Software"
theme = ["wisteria", "hugo-solstice-theme"]
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The Eclipse Foundation provides our global community of individuals and organizations with a mature, scalable, and business-friendly environment for open source software collaboration and innovation."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse", "project", "i18n", "l10n", "C++", "lint", "qt", "wxWidgets"]
  gcse = "011805775785170369411:p3ec0igo0qq"
  gcse_result_url = "https://www.eclipse.org/home/search/"
  hide_call_for_action = true
  call_for_action_text = "Download"
  call_for_action_url = "//eclipse.org/downloads/"
  call_for_action_icon = "fa-download"
  layout_style = "astro"
  hide_ad = true
  featured_content_publish_target = "eclipse_org"
  sidebar_layout = "default"
  logo = "images/app-logo.png"
  favicon = "images/app-logo.png"
  share_img = "images/app-logo.png"
# js = ""
# styles = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
# projects_working_group = ""
# show_events = true
# table_classes = "table table-bordered"
# hide_cfa_same_page = true
# show_collapsible_menu = true

[taxonomies]
  tag = "tags"

[Author]
  name = "Eclipse Foundation"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "eclipsefdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
